db:
  image: dockerfile/mongodb
  command: mongod --smallfiles
  ports:
    - "27017"
    - "28017"
web:
  build: .
  command: bash run.sh
  environment:
    - CLOUDINARY_URL=URL
  volumes:
    - .:/workspace
  ports:
    - "3000:3000"
  links:
    - db
