test:
  sessions:
    default:
      database: type_station_test
      hosts:
        - db:27017
development:
  sessions:
    default:
      database: type_station_development
      hosts:
        - db:27017
